version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default:
        ipv4_address: 172.21.0.249
  user:
    image: xinyifly/php-composer
    volumes:
      - ./user:/mnt
    working_dir: /mnt
    command: php artisan serve --host=0.0.0.0 --port=80
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=api.btcexc.armlfs.org.local
networks:
  default:
    external:
      name: nginx-proxy
